flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired
from flaskblog import conn

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Submit')

class UpdateForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()],default= "")
    content = TextAreaField('Content', validators=[DataRequired()],default= "")
    submit = SubmitField('Submit')

    

flaskblog/posts/routes.py
  
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint, session
from flaskblog import conn
from flaskblog.posts.forms import PostForm, UpdateForm

posts = Blueprint('posts',__name__)

@posts.route("/post/new", methods=['GET', 'POST'])
def new_post():
    if "isAuthenticated" in session:
        if session["isAuthenticated"]:
            form = PostForm()
            if form.validate_on_submit():
                c = conn.cursor()
                c.execute(f"INSERT INTO post (title, date_posted, content, user_id) VALUES ('{form.title.data}', datetime('now'), '{form.content.data}', {int(session['userID'])})")
                conn.commit()
                flash('Your Post has been created!', 'success')
                return redirect(url_for('main.home'))
        else:
            flash('Please Login again to create new post','info')
            return redirect(url_for('users.login'))
    else:
            flash('Please Login to create new post','info')
            return redirect(url_for('users.login'))
    return render_template('create_post.html', title = 'New Post', form = form, legend = 'New Post')
    

@posts.route('/post/<int:post_id>', methods=['GET', 'POST'])
def post(post_id):
    updateable = False
    c = conn.cursor()
    c.execute(f"SELECT user.username, post.title, post.content, post.date_posted, user.image_file, post.id FROM post LEFT JOIN user ON user.id = post.user_id WHERE post.id = {post_id}")
    item = c.fetchone()
    post = {
        'author': item[0],
        'title': item[1],
        'content': item[2],
        'date_posted': item[3],
        'image_file': item[4],
        'id': item[5]
    }
    if "isAuthenticated" in session:
        if session["isAuthenticated"]:
            c = conn.cursor()
            c.execute(f"SELECT user_id FROM post WHERE id = {post_id}")
            if int(c.fetchone()[0]) == int(session['userID']):
                updateable = True
    return render_template('post.html', title=post['title'], post=post, updateable = updateable)

@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
def update_post(post_id):
    if "isAuthenticated" in session:
        if session["isAuthenticated"]:
            c = conn.cursor()
            c.execute(f"SELECT user_id FROM post WHERE id = {post_id}")
            if int(c.fetchone()[0]) != int(session['userID']):
                abort(403)
            form = UpdateForm()
            c.execute(f"SELECT title, content FROM post WHERE id = {post_id}")
            default = c.fetchone()
            default_title = default[0]
            default_content = default[1]
            if form.validate_on_submit():
                c = conn.cursor()
                c.execute(f"UPDATE post SET title = '{form.title.data}', content = '{form.content.data}' WHERE id = {post_id}")
                conn.commit()

                flash('Your Post has been Updated!', 'success')
                return redirect(url_for('posts.post', post_id=post_id))
        else:
            flash('Please Login again to update post','info')
            return redirect(url_for('users.login'))
    else:
        flash('Please Login to update post','info')
        return redirect(url_for('users.login'))
    
    return render_template('create_post.html', title = 'New Post', form = form, legend = 'Update Post', default_content = default_content, default_title = default_title)

@posts.route('/post/<int:post_id>/delete', methods=['GET', 'POST'])
def delete_post(post_id):
    if "isAuthenticated" in session:
        if session["isAuthenticated"]:
            c = conn.cursor()
            c.execute(f"SELECT user_id FROM post WHERE id = {post_id}")
            if int(c.fetchone()[0]) != int(session['userID']):
                abort(403)

            c = conn.cursor()
            c.execute(f"DELETE FROM post WHERE id = {post_id}")
            conn.commit()

            flash('Your Post has been Deleted!', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Please Login again to delete post','info')
            return redirect(url_for('users.login'))
    else:
        flash('Please Login to delete post','info')
        return redirect(url_for('users.login'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, session
from flaskblog import bcrypt, conn
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from flaskblog.users.utils import save_picture

users = Blueprint('users',__name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    fielderror = {}
    form = RegistrationForm()
    c = conn.cursor()
    
    c.execute(f"SELECT id FROM user WHERE email = '{form.email.data}'")
    isEmail = c.fetchone()
    c.execute(f"SELECT id FROM user WHERE username = '{form.username.data}'")
    isUsername = c.fetchone()

    if isEmail:
        fielderror['email'] = 'This Email is already taken.'
    if isUsername:
        fielderror['username'] = 'This Usernanme is already taken.'

    if form.validate_on_submit() and not isUsername and not isEmail:

        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        c = conn.cursor()
        c.execute(f"INSERT INTO user(username, email, password) VALUES ('{form.username.data}','{form.email.data}','{hashed_password}')")

        conn.commit()
        flash(f'Account created for {form.username.data}!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form, fielderror = fielderror)


@users.route("/login", methods=['GET', 'POST'])
def login():
    #login data
    form = LoginForm()
    
    #is entered value valid?
    if form.validate_on_submit():

        #cursor for database connection
        c = conn.cursor()
        c.execute(f"SELECT password FROM user WHERE email = '{form.email.data}'")
        password = c.fetchone()
        #authentication
        if password == None:
            flash('Login Unsuccessfull, Given username does not exist', 'danger')
        elif bcrypt.check_password_hash(password[0],form.password.data):

            #creating session storage
            c.execute(f"SELECT id FROM user WHERE email = '{form.email.data}'")
            session.permanent = False
            session['userID'] = f"{c.fetchone()[0]}"
            session["isAuthenticated"] = True
            
            flash(f'Login Successfull, Welcome   to flaskblog', 'success')
            return redirect(url_for('main.home'))
            
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout", methods=['GET', 'POST'])
def logout():
    session.pop("userID", None)
    session["isAuthenticated"] = False

    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
def account():
    if "isAuthenticated" in session:

        #REAL ACCOUNT PAGE
        if session["isAuthenticated"]:
            fielderror = {}
            form = UpdateAccountForm()
            
            c = conn.cursor()
            c.execute(f"SELECT * FROM user WHERE id = '{session['userID']}'")
            data = c.fetchone()
            current_user = {
                'id': data[0],
                'username': data[1],
                'email':data[2],
                'image_file': data[3]
            }
            image_file = url_for('static', filename = 'profile_pics/' + current_user['image_file'])

            c = conn.cursor()
            c.execute(f"SELECT user.username, post.title, post.content, post.date_posted, user.image_file, post.id FROM post LEFT JOIN user ON user.id = post.user_id WHERE user.username = '{current_user['username']}'")

            items = c.fetchall()
            posts = []
            for item in items:
                post = {
                    'author': item[0],
                    'title': item[1],
                    'content': item[2],
                    'date_posted': item[3],
                    'image_file': item[4],
                    'id': item[5]
                }
                posts.append(post)
            c = conn.cursor()
   
            c.execute(f"SELECT id FROM user WHERE email = '{form.email.data}' AND email <> '{current_user['email']}'")       
            isEmail = c.fetchone()
            c.execute(f"SELECT id FROM user WHERE username = '{form.username.data}' AND username <> '{current_user['username']}'")
            isUsername = c.fetchone()

            if isEmail:
                fielderror['email'] = 'This Email is already taken.'
            if isUsername:
                fielderror['username'] = 'This Usernanme is already taken.'

            if form.validate_on_submit() and not isUsername and not isEmail:
                c = conn.cursor()

                if form.picture.data:
                    picture_file = save_picture(form.picture.data)
                    c.execute(f"UPDATE user SET image_file = '{picture_file}' WHERE id = {int(session['userID'])}")
                if form.username.data:
                    c.execute(f"UPDATE user SET username = '{form.username.data}' WHERE id = {int(current_user['id'])}")     
                if form.email.data:
                    c.execute(f"UPDATE user SET email = '{form.email.data}' WHERE id = {int(current_user['id'])}")
                conn.commit()
                flash(f'Account Updated to {form.username.data}!', 'success')
                return redirect(url_for('users.account'))
            

        else:
            flash('Please Login to access Account Page','info')
            return redirect(url_for('users.login'))
    else:
        flash('Please Login to access Account Page','info')
        return redirect(url_for('users.login'))

    return render_template('account.html',title='Account',current_user = current_user,image_file = image_file, form=form, fielderror= fielderror, posts = posts)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}  

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
        </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
    
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
    
                    {% if form.username.errors or fielderror.username %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                            {{ fielderror.username }}
                        </div>
                    {% else %}
    
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors or fielderror.email %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                            {{ fielderror.username }}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class = "form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <h2>My Posts</h2><br>
    {% for post in posts %}
        <article class="media content-section">
            <img src="{{ url_for('static', filename='profile_pics/'+post.image_file) }}" alt="" class="rounded-circle article-img">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="#">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
            <img src="{{ url_for('static', filename='profile_pics/'+post.image_file) }}" alt="" class="rounded-circle article-img">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="#">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Flask Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="/">Home</a>
                        <a class="nav-item nav-link" href="/about">About</a>
                    </div>

                  <!-- Navbar Right Side -->
                  <div class="navbar-nav">
                      {% if session.isAuthenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                      {% else %}
                        <a class="nav-item nav-link" href="/login">Login</a>
                        <a class="nav-item nav-link" href="/register">Register</a>
                      {% endif %}
                  </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8"> 
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}" role="alert">
                            {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}

                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Attention Bar</h3>
                    <p class='text-muted'>We put important information here that need your attention.
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-light">New</li>
                            <li class="list-group-item list-group-item-light">Event</li>
                            <li class="list-group-item list-group-item-light">Calendars</li>
                            <li class="list-group-item list-group-item-light">etc</li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <img src="{{ url_for('static', filename='profile_pics/'+post.image_file) }}" alt="" class="rounded-circle article-img">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="#">{{ post.author }}</a>
                <small class="text-muted">{{ post.date_posted }}</small>
                {% if updateable %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </div>
                {% endif %}
            </div>
            <h2><a class="article-title" href="#"></a>{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
            </div>
        </div>
        </div>
    </div>
{% endblock content %}

flaskblog/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors or fielderror.username %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                            {{ fielderror.username }}
                        </div>
                    {% else %}
                        
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors or fielderror.email %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                            {{ fielderror.username }}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1>{{ author }} Posts</h1><br>
    {% for post in posts %}
        <article class="media content-section">
            <img src="{{ url_for('static', filename='profile_pics/'+post.image_file) }}" alt="" class="rounded-circle article-img">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="#">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}  